#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
enum {
    CT_A_1,
    CT_S_2,
    CT_D_3,
    CT_F_4,
    CT_G_5,
    CT_H_6,
    CT_J_7,
    CT_K_8,
    CT_L_9,
    CT_SCLN_0
};

typedef struct {
    uint16_t tap;
    uint16_t hold;
    uint16_t held;
} tap_dance_tap_hold_t;


void tap_dance_tap_hold_finished(tap_dance_state_t *state, void *user_data) {
    tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)user_data;

    if (state->pressed) {
        if (state->count == 1
#ifndef PERMISSIVE_HOLD
            && !state->interrupted
#endif
        ) {
            register_code16(tap_hold->hold);
            tap_hold->held = tap_hold->hold;
        } else {
            register_code16(tap_hold->tap);
            tap_hold->held = tap_hold->tap;
        }
    }
}

void tap_dance_tap_hold_reset(tap_dance_state_t *state, void *user_data) {
    tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)user_data;

    if (tap_hold->held) {
        unregister_code16(tap_hold->held);
        tap_hold->held = 0;
    }
}

#define ACTION_TAP_DANCE_TAP_HOLD(tap, hold) \
    { .fn = {NULL, tap_dance_tap_hold_finished, tap_dance_tap_hold_reset}, .user_data = (void *)&((tap_dance_tap_hold_t){tap, hold, 0}), }


tap_dance_action_t tap_dance_actions[] = {
    [CT_A_1] = ACTION_TAP_DANCE_TAP_HOLD(KC_A, KC_1),
    [CT_S_2] = ACTION_TAP_DANCE_TAP_HOLD(KC_S, KC_2),
    [CT_D_3] = ACTION_TAP_DANCE_TAP_HOLD(KC_D, KC_3),
    [CT_F_4] = ACTION_TAP_DANCE_TAP_HOLD(KC_F, KC_4),
    [CT_G_5] = ACTION_TAP_DANCE_TAP_HOLD(KC_G, KC_5),
    [CT_H_6] = ACTION_TAP_DANCE_TAP_HOLD(KC_H, KC_6),
    [CT_J_7] = ACTION_TAP_DANCE_TAP_HOLD(KC_J, KC_7),
    [CT_K_8] = ACTION_TAP_DANCE_TAP_HOLD(KC_K, KC_8),
    [CT_L_9] = ACTION_TAP_DANCE_TAP_HOLD(KC_L, KC_9),
    [CT_SCLN_0] = ACTION_TAP_DANCE_TAP_HOLD(KC_SCLN, KC_0)
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_TAB, [CT_A_1], [CT_S_2], [CT_D_3], [CT_F_4], [CT_G_5], [CT_H_6], [CT_J_7], [CT_K_8], [CT_L_9], [CT_SCLN_0], KC_ENT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_NUHS, KC_LCTL, KC_LGUI, LALT_T(KC_UNDS), LT(1,KC_SPC), LT(1,KC_SPC), MO(3), MO(2), LT(4,KC_NUBS), KC_QUOT),
	[1] = LAYOUT(KC_ESC, KC_NO, KC_BTN1, KC_MS_U, KC_BTN2, KC_NO, KC_NO, KC_DEL, KC_UP, KC_BSPC, KC_NO, KC_DEL, KC_NO, KC_NO, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_HOME, KC_LEFT, KC_DOWN, KC_RGHT, KC_END, KC_ENT, KC_PGUP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PGUP, KC_PGDN, KC_DEL, KC_UP, KC_BSPC, KC_PGDN, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT),
	[2] = LAYOUT(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, KC_PPLS, KC_PMNS, KC_ASTR, KC_PSLS, KC_EQL, KC_PERC, KC_NO, KC_NO, KC_DOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DOT, KC_DOT, KC_NO, KC_TRNS, KC_NO, KC_NO),
	[3] = LAYOUT(KC_GRV, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL, KC_TAB, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LCBR, KC_RCBR, KC_ENT, KC_NO, KC_PPLS, KC_PMNS, KC_ASTR, KC_PSLS, KC_EQL, KC_PERC, KC_NO, KC_NO, KC_LBRC, KC_RBRC, KC_BSLS, KC_NO, KC_NO, KC_MINS, KC_UNDS, KC_UNDS, KC_TRNS, KC_NO, KC_NO, KC_QUOT),
	[4] = LAYOUT(RGB_M_P, RGB_M_B, RGB_M_R, RGB_M_SW, RGB_M_SN, RGB_M_K, RGB_M_X, RGB_M_G, RGB_M_T, RGB_RMOD, RGB_MOD, RGB_TOG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_SPD, RGB_SPI, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_VAD, RGB_VAI, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_HUD, RGB_HUI, KC_TRNS, KC_VOLD)
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    tap_dance_action_t *action;

    switch (keycode) {
        case TD(CT_A_1):  // list all tap dance keycodes with tap-hold configurations
        case TD(CT_S_2):
        case TD(CT_D_3):
        case TD(CT_F_4):
        case TD(CT_G_5):
        case TD(CT_H_6):
        case TD(CT_J_7):
        case TD(CT_K_8):
        case TD(CT_L_9):
        case TD(CT_SCLN_0):
            action = &tap_dance_actions[TD_INDEX(keycode)];
            if (!record->event.pressed && action->state.count && !action->state.finished) {
                tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)action->user_data;
                tap_code16(tap_hold->tap);
            }
    }
    return true;
}

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
